extends Node

var TILE_SIZE = 8

var PLAYER_WALK_SPEED = (5.5 * TILE_SIZE)
var PLAYER_WALK_TRANSITION_WEIGHT = (0.4)
var PLAYER_WALK_FRICTION = (0.06)

var PLAYER_MAX_JUMP_HEIGHT =  (4.50 * TILE_SIZE)
var PLAYER_MIN_JUMP_HEIGHT = (1.2 * TILE_SIZE)
var PLAYER_JUMP_DURATION = 0.45

var PLAYER_TERMINAL_VELOCITY = (400.0)
var PLAYER_GRAVITY = (2 * PLAYER_MAX_JUMP_HEIGHT) / pow(PLAYER_JUMP_DURATION, 2)
var PLAYER_MAX_JUMP_SPEED = (sqrt(2 * PLAYER_GRAVITY * PLAYER_MAX_JUMP_HEIGHT))
var PLAYER_MIN_JUMP_SPEED = (sqrt(2 * PLAYER_GRAVITY * PLAYER_MIN_JUMP_HEIGHT))

var PLAYER_TOP_SPRINT_SPEED = (8.5 * TILE_SIZE)
var PLAYER_SPRINT_TRANSITION_WEIGHT = (0.3)

var PLAYER_TURBO_SLIDE_SPEED = (14.5 * TILE_SIZE)

var PLAYER_HIGH_SPEED_LANDING_MOMENTUM_LOSS_TIME = 0.44
var PLAYER_HIGH_SPEED_LANDING_MOMENTUM_LOSS = ((PLAYER_TURBO_SLIDE_SPEED - PLAYER_TOP_SPRINT_SPEED) / PLAYER_HIGH_SPEED_LANDING_MOMENTUM_LOSS_TIME)

var PLAYER_SLIDE_DECELERATION_TIME = 1.4
var PLAYER_SLIDE_DECELERATION = ((PLAYER_TURBO_SLIDE_SPEED - PLAYER_WALK_SPEED) / PLAYER_SLIDE_DECELERATION_TIME)
var PLAYER_SLIDE_GRAVITY = (30.0 * TILE_SIZE)

var PLAYER_SLIDE_NEGATION_DECELERATION_TIME = 0.35
var PLAYER_SLIDE_NEGATION_DECELERATION = ((PLAYER_TURBO_SLIDE_SPEED - PLAYER_WALK_SPEED) / PLAYER_SLIDE_NEGATION_DECELERATION_TIME)

var PLAYER_DECELERATE_FROM_SPRINT_TO_WALK_TIME = 0.65
var PLAYER_STOP_SPRINT_DECELERATION = ((PLAYER_TOP_SPRINT_SPEED - PLAYER_WALK_SPEED) / PLAYER_DECELERATE_FROM_SPRINT_TO_WALK_TIME)

var PLAYER_DECELERATE_SPRINT_BY_TURN_TIME = 0.42
var PLAYER_RESIST_SPRINT_DECELERATION = ((PLAYER_TOP_SPRINT_SPEED - PLAYER_WALK_SPEED) / PLAYER_DECELERATE_SPRINT_BY_TURN_TIME)

var PLAYER_DECELERATE_FROM_AIR_TO_STOP_TIME = 0.32
var PLAYER_STOP_MID_AIR_DECELERATION = (PLAYER_WALK_SPEED / PLAYER_DECELERATE_FROM_AIR_TO_STOP_TIME)

var PLAYER_DECELERATE_SPRINT_IN_AIR_BY_TURN_TIME = 0.1
var PLAYER_DECELERATE_SPRINT_IN_AIR_NORMALLY_TIME = 1.1
var PLAYER_STOP_SPRINT_IN_AIR_DECELERATION = ((PLAYER_TOP_SPRINT_SPEED - PLAYER_WALK_SPEED) / PLAYER_DECELERATE_SPRINT_IN_AIR_NORMALLY_TIME)
